
export const columns = [
  { field: "id", headerName: "ID", width: 33 },
  { field: "registrarId", headerName: "Registrar ID" },
  {
    field: "name",
    headerName: "Name",
    flex: 1,
    cellClassName: "name-column--cell",
  },
  {
    field: "age",
    headerName: "Age",
    type: "number",
    headerAlign: "left",
    align: "left",
    flex: 1,
  },
  {
    field: "phone",
    headerName: "Phone Number",
    flex: 1,
  },
  {
    field: "email",
    headerName: "Email",
    flex: 1,
  },
  {
    field: "address",
    headerName: "Address",
    flex: 1,
  },
  {
    field: "city",
    headerName: "City",
    flex: 1,
  },
  {
    field: "zipCode",
    headerName: "Zip Code",
  },
];

export const rows = [
  {
    id: 1,
    name: "Random",
    email: "random@gmail.com",
    age: 35,
    phone: "(665)121-5454",
    address: "hussein fuqaha Street, Amman",
    city: "albayader",
    zipCode: "10001",
    registrarId: 123512,
  },
  {
    id: 2,
    name: "Random",
    email: "random@gmail.com",
    age: 42,
    address: "hussein fuqaha Street, Amman",
    city: "albayader",
    city: "New York",
    zipCode: "13151",
    registrarId: 123512,
  },
  {
    id: 3,
    name: "Random",
    email: "random@gmail.com",
    age: 45,
    phone: "(422)982-6739",
    address: "hussein fuqaha Street, Amman",
    city: "albayader",
    zipCode: "87281",
    registrarId: 4132513,
  },
  {
    id: 4,
    name: "Random",
    email: "random@gmail.com",
    age: 16,
    phone: "(921)425-6742",
    address: "hussein fuqaha Street, Amman",
    city: "albayader",
    zipCode: "15551",
    registrarId: 123512,
  },
  {
    id: 5,
    name: "Random",
    email: "random@gmail.com",
    age: 31,
    phone: "(421)445-1189",
    address: "hussein fuqaha Street, Amman",
    city: "albayader",
    zipCode: "14215",
    registrarId: 123512,
  },
  {
    id: 6,
    name: "Random",
    email: "random@gmail.com",
    age: 150,
    phone: "(232)545-6483",
    address: "hussein fuqaha Street, Amman",
    city: "albayader",
    zipCode: "10001",
    registrarId: 123512,
  },
  {
    id: 7,
    name: "Random",
    email: "random@gmail.com",
    age: 44,
    phone: "(543)124-0123",
    address: "hussein fuqaha Street, Amman",
    city: "albayader",
    zipCode: "51523",
    registrarId: 123512,
  },
  {
    id: 8,
    name: "Random",
    email: "random@gmail.com",
    age: 36,
    phone: "(222)444-5555",
    address: "hussein fuqaha Street, Amman",
    city: "albayader",
    zipCode: "44215",
    registrarId: 512315,
  },
  {
    id: 9,
    name: "Random",
    email: "random@gmail.com",
    age: 65,
    phone: "(444)555-6239",
    address: "hussein fuqaha Street, Amman",
    city: "albayader",
    zipCode: "111234",
    registrarId: 928397,
  },
  {
    id: 10,
    name: "Random",
    email: "random@gmail.com",
    age: 42,
    phone: "(222)444-5555",
    address: "hussein fuqaha Street, Amman",
    city: "albayader",
    zipCode: "44215",
    registrarId: 533215,
  },
  {
    id: 11,
    name: "Random",
    email: "random@gmail.com",
    age: 11,
    phone: "(444)555-6239",
    address: "hussein fuqaha Street, Amman",
    city: "albayader",
    zipCode: "1234",
    registrarId: 92197,
  },
];
